### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by ivandrodri** [alpaka-group/mallocMC#195]
Hello,

I would like to use a heap device memory pool in my project to speed up the dynamical allocations/deallocations. I included mallocMC in my code but it is slower than the standard CUDA malloc/free operations. I would like to know if I am doing something wrong and if mallocMC could be a good option for my project. 

I have in my code a struct like this:

```C++
struct Obj{
unsigned int* bitMap;
}
```

and I create objects like the one below on the device:

```C++
Obj* obj;
size_t dimObj = 30 * 30 * 30;
cudaMalloc( (void**)&obj, dimObj*sizeof(Obj));
```

the bitMap pointers in obj are created and destroyed dynamically inside the kernels and their could be large like 40 * 40 * 40, for instance.

I am using the config file in the repository's example:

```C++
///////////////////////////////////////////////////////////////////////////////
// includes for mallocMC
///////////////////////////////////////////////////////////////////////////////
// basic files for mallocMC
#include <mallocMC/mallocMC_hostclass.hpp>

// Load all available policies for mallocMC
#include <mallocMC/AlignmentPolicies.hpp>
#include <mallocMC/CreationPolicies.hpp>
#include <mallocMC/DistributionPolicies.hpp>
#include <mallocMC/OOMPolicies.hpp>
#include <mallocMC/ReservePoolPolicies.hpp>
#include <mallocMC/ReservePoolPolicies.hpp>

///////////////////////////////////////////////////////////////////////////////
// Configuration for mallocMC
///////////////////////////////////////////////////////////////////////////////

// configurate the CreationPolicy "Scatter"
struct ScatterConfig
{
    static constexpr auto pagesize = 4096;
    static constexpr auto accessblocks = 8;
    static constexpr auto regionsize = 16;
    static constexpr auto wastefactor = 2;
    static constexpr auto resetfreedpages = false;
};

struct ScatterHashParams
{
    static constexpr auto hashingK = 38183;
    static constexpr auto hashingDistMP = 17497;
    static constexpr auto hashingDistWP = 1;
    static constexpr auto hashingDistWPRel = 1;
};

// configure the DistributionPolicy "XMallocSIMD"
struct DistributionConfig
{
    static constexpr auto pagesize = ScatterConfig::pagesize;
};

// configure the AlignmentPolicy "Shrink"
struct AlignmentConfig
{
    static constexpr auto dataAlignment = 16;
};

// Define a new mMCator and call it ScatterAllocator
// which resembles the behaviour of ScatterAlloc
using ScatterAllocator = mallocMC::Allocator<
    mallocMC::CreationPolicies::Scatter<ScatterConfig, ScatterHashParams>,
    mallocMC::DistributionPolicies::XMallocSIMD<DistributionConfig>,
    mallocMC::OOMPolicies::ReturnNull,
    mallocMC::ReservePoolPolicies::SimpleCudaMalloc,
    mallocMC::AlignmentPolicies::Shrink<AlignmentConfig>>;

///////////////////////////////////////////////////////////////////////////////
// End of mallocMC configuration
///////////////////////////////////////////////////////////////////////////////
```

Thanks for any help!

[updated formation]

**Comment by psychocoderHPC** [comment]
I will have a look into this issue/question on Wednesday when I am back in the office.

**Comment by psychocoderHPC** [comment]
I suggest to have a short look into https://zenodo.org/record/34461#.X6EM6oZ7mUk. mallocMC with scatter alloc is using a hierarchical tree to maintain the heap. Depending on the settings and distribution policy configuration the performance will variate.

In you case  you used the default parameter with 4kiB pages and allocated `30*30*30*8` bytes or more. IN that case the allocator is combining pages to one large allocation, this is very slow.

My suggestion is to increase the page size to hold multiple allocations on one page. A page can have multiple regions and each region can hold up to 32 chunks.
I will use your worst case scenario `40*40*40*8 byte` as base for a configuration. Please keep in mind that depending on the assumt chunk size it could be that you can't use 100% of the configured heap.

`(40 * 40 * 40 * 8) * 32 * 16 = 262144000` will result into a 262MiB page. I also suggest to set `resetfreedpages = true` to free pages if they are empty. A page can hold only chunks of one size, since you allocate always different sizes it is useful to free empty pages to allow a re-allocation with a different size.

```
struct ScatterConfig
{
    static constexpr auto pagesize = 262144000;
    static constexpr auto accessblocks = 8;
    static constexpr auto regionsize = 16;
    static constexpr auto wastefactor = 2;
    static constexpr auto resetfreedpages = true;
};
```

I also suggest to change the distribution policy to `mallocMC::DistributionPolicies::Noop`.  `XMallocSIMD` is collecting all allocations at the same time within one warp and is so allocating larger chunks. This method is useful if all threads will allocate and free memory at the same time but the page size should than also be adjusted. The drawback is that memory fragments faster.

```
using ScatterAllocator = mallocMC::Allocator<
    mallocMC::CreationPolicies::Scatter<ScatterConfig, ScatterHashParams>,
    mallocMC::DistributionPolicies::Noop,
    mallocMC::OOMPolicies::ReturnNull,
    mallocMC::ReservePoolPolicies::SimpleCudaMalloc,
    mallocMC::AlignmentPolicies::Shrink<AlignmentConfig>>;
```

**Comment by ivandrodri** [comment]
@psychocoderHPC : Thanks a lot for the info! I will try it and I let you know.

**Comment by psychocoderHPC** [comment]
@ivandrodri please note that we move the repository of malocMC to a new organization, the link is now https://github.com/alpaka-group/mallocMC

**Comment by chillenzer** [comment]
Did this help you? I would suggest to close this issue.

**Comment by ivandrodri** [comment]
@chillenzer yes it was helpful! You can close the issue and thanks!

**Comment by chillenzer** [comment]
Great! Good to hear!
